version: '3.5'

services:
  hapi_db:
    container_name: hapi-mysql
    build: ./mysql
    # image: mysql:5.6
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "33060:3306"
    networks:
      - web_server
  hapi_http:
    container_name: hapi-http
    build: .
    ports:
      - '8080:8080'
      # - '443:443'
    depends_on:
      - hapi_db
    networks:
      - web_server
volumes:
    db_data:
networks:
  web_server:
    # external:
    #   name: carespan_hapi_network
